In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
# tensor with one axis = vector
# tensor with 2 axes = matrix
# tensor with k > 2 axes = K(th) order tensor

# values of a tensor are called elements

In [6]:
x.numel() # get total number of elements

12

In [8]:
x.shape

torch.Size([12])

In [10]:
x = x.reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
x = x.reshape(-1, 4) #same result when (3, -1)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.randn(3, 4)

tensor([[-1.3850,  1.1560, -0.5229,  0.4058],
        [ 1.0259, -1.4506,  2.3502,  0.3812],
        [ 0.7994,  1.9119,  1.2753,  0.0854]])

In [14]:
torch.tensor([[2,3,4,5], [0,9,8,5], [5,7,2,9]])

tensor([[2, 3, 4, 5],
        [0, 9, 8, 5],
        [5, 7, 2, 9]])

In [15]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [16]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
x[0]

tensor([0., 1., 2., 3.])

In [18]:
x[0, 3] = 23 # assign element with value
x

tensor([[ 0.,  1.,  2., 23.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
x[0,1]

tensor(1.)

In [20]:
torch.exp(x)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 9.7448e+09],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [21]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [32]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0),torch.cat((X, Y), dim=1) # concatenating two tensors by both axes

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  2.,  6.,  6.],
         [ 4.,  5.,  6.,  7.,  5.,  7.,  9., 11.],
         [ 8.,  9., 10., 11., 12., 12., 12., 12.]]))

In [27]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
x.sum()

tensor(66.)

In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b # for tensors of different shapes, we use broadcasting mechanism

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [33]:
before = id(y)
y = y + x
id(y) == before

False

In [34]:
z = torch.zeros_like(y)
print('id(Z):', id(z))
z[:] = x + y # slice notation is used to avoid allocation new memory
print('id(Z):', id(z))

id(Z): 1656668440832
id(Z): 1656668440832


In [35]:
before = id(X)
X += Y
id(X) == before #same location in memory

True

In [36]:
_a = x.numpy()
_b = torch.from_numpy(_a)
type(_a), type(_b) # conversion

(numpy.ndarray, torch.Tensor)

In [37]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [38]:
x, y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

In [39]:
x < y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [40]:
x > y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
x[0, 0] = 10
x < y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])